books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('book_list/', views.book_list, name='book_list'),
    path('authors/', views.author_list, name='author_list'),
    path('authors/add/', views.add_author, name='add_author'),
    path('authors/<int:pk>/', views.author_detail, name='author_detail'),
    path('books/add/', views.add_book, name='add_book'),
    path('edit/<int:pk>/', views.edit_book, name='edit_book'),  # Ensure this pattern exists
    path('delete/<int:pk>/', views.delete_book, name='delete_book'),  
    path('author/edit/<int:pk>/', views.edit_author, name='edit_author'),  # Edit author URL pattern
    path('author/delete/<int:pk>/', views.delete_author, name='delete_author'),  # Delete author URL pattern
    path('categories/', views.category_list, name='category_list'),
    path('categories/new/', views.category_create, name='category_create'),
    path('categories/<int:pk>/edit/', views.category_update, name='category_update'),
    path('categories/<int:pk>/delete/', views.category_delete, name='category_delete'),

]   

core/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('',include('mpi.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('users.urls')),
    path('book/',include('books.urls')),
    path('order/',include('library.urls')),
   
    path('',include('accounts.urls')),
   
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models 
from users.models import User
import pycountry

class Author(models.Model):
    COUNTRY_NAME_CHOICES = [('SL', 'Select Country Name')] + [
    (country.alpha_2, country.name) for country in pycountry.countries
]
   

    image=models.ImageField(
        upload_to='author_image/',
        blank=True,
        null=True
    )
    name= models.CharField(max_length=255)
    bio=models.TextField(blank=True)
    date_of_birth=models.DateField(null=True,blank=True)
    country=models.CharField(
        max_length=30,
        choices=COUNTRY_NAME_CHOICES,
        default='SL',
        )
    
    def __str__(self):
        return self.name
   

class BookCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    
class Book(models.Model):
    LANGUAGE_NAME_CHOICES = [
    ('BD', 'Bangla'),
    ('PK', 'Urdu'),
    ('LN', 'Select Book Language'),
    ('IN', 'Hindi'),
    ('EN', 'English'),
    ('FR', 'French'),
    ('ES', 'Spanish'),
    ('DE', 'German'),
    ('CN', 'Mandarin'),
    ('JP', 'Japanese'),
    ('RU', 'Russian'),
    ('IT', 'Italian'),
    ('PT', 'Portuguese'),
    ('AR', 'Arabic'),
    ('KR', 'Korean'),
    ('TR', 'Turkish'),
]
    image = models.ImageField(
        upload_to='book_image/',
        blank=True,
        null=True 
    )
    
    title = models.CharField(max_length=255)
    entry_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(BookCategory, on_delete=models.CASCADE, null=True, blank=True)
    isbn = models.CharField(max_length=13)
    published_date = models.DateField()
    language=models.CharField(
        max_length=30,
        choices=LANGUAGE_NAME_CHOICES,
        default='LN',
        )
    available_copies = models.IntegerField()
    
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from .models import Author, Book

from django import forms
from .models import BookCategory

class BookCategoryForm(forms.ModelForm):
    class Meta:
        model = BookCategory
        fields = ['name', 'description']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = [ 'image','name', 'bio', 'date_of_birth', 'country']

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['image','title', 'author', 'category', 'isbn', 'published_date', 'language', 'available_copies',  'description']

books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Author, Book, BookCategory
from .forms import AuthorForm, BookForm ,BookCategoryForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')
def author_list(request):
    authors = Author.objects.all()
    return render(request, 'books/author_list.html', {'authors': authors})

@login_required(login_url='/login/')
def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'books/author_detail.html', {'author': author})

@login_required(login_url='/login/')
def add_author(request):
    
    if request.method == "POST":
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('author_list')
    else:
        form = AuthorForm()
    return render(request, 'books/author_form.html', {'form': form})

@login_required(login_url='/login/')
def edit_author(request, pk):
    
    author = get_object_or_404(Author, pk=pk)
    if request.method == 'POST':
        form = AuthorForm(request.POST, instance=author)
        if form.is_valid():
            form.save()
            return redirect('author_list')  # Replace with the actual list view for authors
    else:
        form = AuthorForm(instance=author)
    return render(request, 'books/edit_author.html', {'form': form, 'author': author})
@login_required(login_url='/login/')
def delete_author(request, pk):
    
    author = get_object_or_404(Author, pk=pk)
    if request.method == 'POST':
        author.delete()
        return redirect('author_list')  # Replace with the actual list view for authors
    return render(request, 'books/author_delete_confirm.html', {'author': author})


@login_required(login_url='/login/')
def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'books': books})

@login_required(login_url='/login/')
def add_book(request):
    
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'books/book_form.html', {'form': form})
@login_required(login_url='/login/')
def edit_book(request, pk):
    
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = BookForm(instance=book)
    return render(request, 'books/edit_book.html', {'form': form, 'book': book})

@login_required(login_url='/login/')
def delete_book(request, pk):
    
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('book_list')  # Assuming 'book_list' is the name of the list view
    return render(request, 'books/delete_confirm.html', {'book': book})




# List all categories
@login_required(login_url='/login/')
def category_list(request):
    categories = BookCategory.objects.all()
    return render(request, 'books/category_list.html', {'categories': categories})

# Create a new category
@login_required(login_url='/login/')
def category_create(request):
    
    if request.method == 'POST':
        form = BookCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = BookCategoryForm()
    return render(request, 'books/category_form.html', {'form': form, 'action': 'Create'})

# Update an existing category
@login_required(login_url='/login/')
def category_update(request, pk):
    
    category = get_object_or_404(BookCategory, pk=pk)
    if request.method == 'POST':
        form = BookCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = BookCategoryForm(instance=category)
    return render(request, 'books/category_form.html', {'form': form, 'action': 'Update'})

# Delete a category
@login_required(login_url='/login/')
def category_delete(request, pk):
    
    category = get_object_or_404(BookCategory, pk=pk)
    if request.method == 'POST':
        category.delete()
        return redirect('category_list')
    return render(request, 'books/category_confirm_delete.html', {'category': category})

templates/books/author_delete_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Are you sure you want to delete the author "{{ author.name }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'author_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock content %}

templates/books/author_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="hero">
<div class="container-fluid px-4">
    <h1 class="mt-4">{{ author.name }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'author_list' %}">Authors</a></li>
        <li class="breadcrumb-item active">{{ author.name }}</li>
    </ol>
    <div class="card mb-4">
        <div class="card-body">
            <img src="{{ author.image.url }}" alt="{{ author.name }}" class="img-fluid mb-3" style="max-width: 200px;">
            <p><strong>Bio:</strong> {{ author.bio }}</p>
            <p><strong>Date of Birth:</strong> {{ author.date_of_birth }}</p>
            <p><strong>Country:</strong> {{ author.get_country_display }}</p>
            {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
            <a href="{% url 'edit_author' author.id %}" class="btn btn-sm btn-warning">Edit</a>
            <a href="{% url 'delete_author' author.id %}" class="btn btn-sm btn-danger">Delete</a>
             {% endif %}
            <a href="{% url 'author_list' %}" class="btn btn-secondary">Back to List</a>

        </div>
    </div>
</div>
</div>
<style>
/* Hero Section */
.hero {
    height: 100vh;
    display: flex;
   
 
    background-image: url('/static/assets/img/dashboard-2li.jpg');
    background-size: cover;
}

.hero .content h1 {
    font-size: 4rem;
    margin-bottom: 20px;
    color: black;
}

.hero .content p {
    font-size: 1.2rem;
    margin-bottom: 30px;
    max-width: 700px;
}
h1{ 
    color: black;
}
</style>
{% endblock content %}

templates/books/author_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Add Author</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'author_list' %}">Authors</a></li>
        <li class="breadcrumb-item active">Add Author</li>
    </ol>
    <div class="card mb-4">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'author_list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/books/author_list.html
{% extends 'base.html' %}

{% block content %}
<div class="hero">
<div class="container-fluid px-4">
    <h1 class="mt-4">Authors</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
        <li class="breadcrumb-item active">Authors</li>
    </ol>
    {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
    <a href="{% url 'add_author' %}" class="btn btn-primary mb-3">Add New Author</a>
    {% endif %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Author List
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Country</th>
                        <th>Date of Birth</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for author in authors %}
                    <tr>
                        <td>
                            {% if author.image %}
                                <img src="{{ author.image.url }}" alt="Author Image" width="50" height="50">
                            {% else %}
                                No Image
                            {% endif %}
                        </td>
                        <td>{{ author.name }}</td>
                        <td>{{ author.get_country_display }}</td>
                        <td>{{ author.date_of_birth }}</td>
                        <td>
                            <a href="{% url 'author_detail' author.pk %}" class="btn btn-info btn-sm">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>

<style>
    /* Hero Section */
.hero {
    height: 100vh;
    display: flex;
   
    background-image: url('/static/assets/img/dashboard-2li.jpg');
    background-size: cover;
}

.hero .content h1 {
    font-size: 4rem;
    margin-bottom: 20px;
    color: black;
}

.hero .content p {
    font-size: 1.2rem;
    margin-bottom: 30px;
    max-width: 700px;
}
h1{ 
    color: black;
}
</style>
{% endblock content %}

templates/books/book_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Add Book</h1>
    <ol class="breadcrumb mb-4">

        <li class="breadcrumb-item"><a href="{% url 'book_list' %}">Books</a></li>
        <li class="breadcrumb-item active">Add Book</li>
    </ol>
    <div class="card mb-4">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'book_list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/books/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="hero">
<div class="container-fluid px-4">
    <h1 class="mt-4">Books</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Dashboard</a></li>
        <li class="breadcrumb-item active">Books</li>
    </ol>
    {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
    <a href="{% url 'add_book' %}" class="btn btn-primary mb-3">Add New Book</a>
    {% endif %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Book List
        </div>
        <div class="card-body">
            <table id="datatablesSimple" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Category</th>
                        <th>Available Copies</th>
                        <th>ISBN</th>
                        <th>Published Date</th>
                        <th>Language</th>
                        {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
                        <th>Actions</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                    <tr>
                        
                        <td>
                            {% if book.image %}
                                <img src="{{ book.image.url }}" alt="Book Image" width="50" height="50">
                            {% else %}
                                No Image
                            {% endif %}
                        </td>
                        <td>{{ book.title }}</td>
                        <td>{{ book.author.name }}</td>
                        <td>{{ book.category.name }}</td>
                        <td>{{ book.available_copies }}</td>
                        <td>{{ book.isbn }}</td>
                        <td>{{ book.published_date }}</td>
                        <td>{{ book.get_language_display }}</td>
                        {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
                        <td>
                            <a href="{% url 'edit_book' book.id %}" class="btn btn-sm btn-warning">Edit</a>
                            <a href="{% url 'delete_book' book.id %}" class="btn btn-sm btn-danger">Delete</a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
<style>


    .book-img {
    width: 50px;
    height: 70px;
    object-fit: cover;
}

.card-header {
    background-color: #f8f9fa;
    font-weight: bold;
}

.btn-sm {
    padding: 5px 10px;
}

.table-striped tbody tr:nth-of-type(odd) {
    background-color: rgba(0, 0, 0, 0.05);
}

    /* Hero Section */
.hero {
    height: 100vh;
    display: flex;
  
    background-image: url('/static/assets/img/dashboard-2li.jpg');
    background-size: cover;
}

.hero .content h1 {
    font-size: 4rem;
    margin-bottom: 20px;
    color: black;
}

.hero .content p {
    font-size: 1.2rem;
    margin-bottom: 30px;
    max-width: 700px;
}
h1{ 
    color: black;
}
</style>

{% endblock content %}

templates/books/category_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1>Delete Category</h1>
    <p>Are you sure you want to delete the category "{{ category.name }}"?</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url 'category_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/books/category_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1>{{ action }} Category</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">{{ action }} Category</button>
        <a href="{% url 'category_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/books/category_list.html
{% extends 'base.html' %}

{% block content %}
<div class="hero">
<div class="container mt-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
    <h1>Book Categories</h1>
    </div>
    {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
    <a href="{% url 'category_create' %}" class="btn btn-primary mb-3">Create New Category</a>
    {% endif %}
    <table id="bookTable" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
                <th>Actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody class="t-bg">
            {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
                <td>
                    <a href="{% url 'category_update' category.pk %}" class="btn btn-warning btn-sm">Edit</a>
                    <a href="{% url 'category_delete' category.pk %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
<style>
    .card-header {
   
    font-weight: bold;
}

.btn-sm {
    padding: 5px 10px;
}
.t-bg{
    background-color: rgba(127, 255, 212, 0.618);
}
.table-striped tbody tr:nth-of-type(odd) {
    background-color: rgba(0, 0, 0, 0.05);
}
       /* Hero Section */
.hero {
    height: 100vh;
    display: flex;
  
    background-image: url('/static/assets/img/dashboard-2li.jpg');
    background-size: cover;
}

.hero .content h1 {
    font-size: 4rem;
    margin-bottom: 20px;
    color: black;
}

.hero .content p {
    font-size: 1.2rem;
    margin-bottom: 30px;
    max-width: 700px;
}
h1{ 
    color: black;
}
</style>
{% endblock %}

templates/books/delete_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Are you sure you want to delete the book "{{ book.title }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'book_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock content %}

templates/books/edit_author.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Edit Author</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-edit me-1"></i>
            Edit Author: {{ author.name }}
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="mb-3">
                    <label for="id_name" class="form-label">Name</label>
                    {{ form.name }}
                </div>
                <div class="mb-3">
                    <label for="id_bio" class="form-label">Bio</label>
                    {{ form.bio }}
                </div>
                <div class="mb-3">
                    <label for="id_date_of_birth" class="form-label">Date of Birth</label>
                    {{ form.date_of_birth }}
                </div>
                <div class="mb-3">
                    <label for="id_country" class="form-label">Country</label>
                    {{ form.country }}
                </div>
                <div class="mb-3">
                    <label for="id_image" class="form-label">Author Image</label>
                    {% if author.image %}
                        <img src="{{ author.image.url }}" alt="{{ author.name }}" class="author-img mb-3">
                    {% endif %}
                    {{ form.image }}
                </div>
                <button type="submit" class="btn btn-primary">Update Author</button>
                <a href="{% url 'author_list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/books/edit_book.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Edit Book</h1>
    <ol class="breadcrumb mb-4">
       
        <li class="breadcrumb-item"><a href="{% url 'book_list' %}">Books</a></li>
        <li class="breadcrumb-item active">Edit Book</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-edit me-1"></i>
            Edit Book: {{ book.title }}
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    {{ form.title }}
                </div>
                <div class="mb-3">
                    <label for="id_author" class="form-label">Author</label>
                    {{ form.author }}
                </div>
                <div class="mb-3">
                    <label for="id_category" class="form-label">Category</label>
                    {{ form.category }}
                </div>
                <div class="mb-3">
                    <label for="id_isbn" class="form-label">ISBN</label>
                    {{ form.isbn }}
                </div>
                <div class="mb-3">
                    <label for="id_published_date" class="form-label">Published Date</label>
                    {{ form.published_date }}
                </div>
                <div class="mb-3">
                    <label for="id_language" class="form-label">Language</label>
                    {{ form.language }}
                </div>
                <div class="mb-3">
                    <label for="id_available_copies" class="form-label">Available Copies</label>
                    {{ form.available_copies }}
                </div>
                <div class="mb-3">
                    <label for="id_image" class="form-label">Book Image</label>
                    {% if book.image %}
                        <img src="{{ book.image.url }}" alt="{{ book.title }}" class="book-img mb-3">
                    {% endif %}
                    {{ form.image }}
                </div>
                <div class="mb-3">
                    <label for="id_description" class="form-label">Description</label>
                    {{ form.description }}
                </div>
                <button type="submit" class="btn btn-primary">Update Book</button>
                <a href="{% url 'book_list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}