core/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('',include('mpi.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('users.urls')),
    path('book/',include('books.urls')),
    path('order/',include('library.urls')),
   
    path('',include('accounts.urls')),
   
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path , include
from . import views

from .views import create_user, update_user, delete_user, all_users ,profile_view

urlpatterns=[
    path('', create_user, name='create_user'), 
    path('profile/', profile_view, name='profile_view'),
    path('update_user_status/<int:user_id>/', views.update_user_status, name='update_user_status'),
    path('update/<int:user_id>/', update_user, name='update_user'),  # URL for user update
    path('delete/<int:user_id>/', delete_user, name='delete_user'),  # URL for user deletion
    path('list/', all_users, name='all_users'),  # URL for listing all users
]

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
import uuid

class UserManager(BaseUserManager):
    def create_user(self, email, name, password=True):
        """
        Creates and saves a User with the given email, name, and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            name=name
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password=None):
        """
        Creates and saves a superuser with the given email, name, and password.
        """
        user = self.create_user(
            email=email,
            password=password,
            name=name
        )
        user.is_admin = True
        user.is_active = True
        
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    USER_TYPE_CHOICES = [
        ('MEM', 'Member'),
        ('LIB', 'Librarian'),
        ('ADM', 'Admin'),
    ]
    USER_TYPE_CHOICES1 = [
        ('CMT', 'Computer Technology'),
        ('ENT', 'Electronics Technology'),
        ('RAC', 'Refrigeration and Air Conditioning Technology'),
        ('FD', 'Food Technology'),
    ]
    image = models.ImageField(upload_to='user_image/', blank=True, null=True)
    email = models.EmailField(verbose_name="email address", max_length=255, unique=True)
    name = models.CharField(max_length=50, blank=True)
    roll = models.PositiveIntegerField(default=0)
    department = models.CharField(max_length=8, choices=USER_TYPE_CHOICES1, default='CMT')
    session = models.CharField(max_length=30, blank=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    membership_number = models.CharField(max_length=50, unique=True, blank=True, null=True)
    user_type = models.CharField(max_length=3, choices=USER_TYPE_CHOICES, default='MEM')
   
   
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)




  

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    def __str__(self):
        return self.email

    def generate_unique_membership_number(self):
        """
        Generates a unique membership number.
        """
        while True:
            membership_number = f'{uuid.uuid4().hex[:8].upper()}'
            if not User.objects.filter(membership_number=membership_number).exists():
                return membership_number

    def save(self, *args, **kwargs):
        if not self.membership_number:
            self.membership_number = self.generate_unique_membership_number()
        super(User, self).save(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin
# models.py


class User1(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    roll = models.IntegerField()
    department = models.CharField(max_length=15, choices=[('CMT', 'Computer Technology'), ('ENT', 'Electronics Technology'),
        ('RAC', 'Refrigeration and Air Conditioning Technology'),
        ('FD', 'Food Technology')])
    session = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.TextField()
    user_type = models.CharField(max_length=3, choices=[('MEM', 'Member'),
     ('LIB', 'Librarian'), ('ADM', 'Admin')])
    image = models.ImageField(upload_to='profiles/', null=True, blank=True)

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from .models import User
from .models import User1

class UserForm1(forms.ModelForm):
    class Meta:
        model = User1
        fields = ['name', 'email', 'roll', 'department', 'session', 'phone_number', 'address', 'user_type', 'image']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'image',
            'name', 
            'email', 
            'roll', 
            'department', 
            'session', 
            'phone_number', 
            'address', 
            'user_type',
            'password' 
            
        ]
        widgets = {
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email'}),
            'roll': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter roll number'}),
            'department': forms.Select(attrs={'class': 'form-control'}),
            'session': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter session'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter phone number'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Enter address'}),
            'user_type': forms.Select(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'}),
            
        }

    # Additional validations if needed
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already registered.")
        return email

users/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import UserForm
from .forms import UserForm1
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def profile_view(request):
    return render(request, 'user/profile.html', {'user': request.user})
@login_required(login_url='login')
def all_users(request):
    
    users = User.objects.all()
    
    query = request.GET.get('q')
    if query:
        users = User.objects.filter(
            Q(email__icontains=query) |
            Q(name__icontains=query) |
            Q(roll__icontains=query) |
            Q(department__icontains=query) |
            Q(membership_number__icontains=query)
        )
    else:
        users = User.objects.all()

    context = {
        'users': users,
        'search_query': query
    }
    context = {
        'users': users
    }
    return render(request, 'user/all_users.html', context)


def create_user(request):
   
    if request.method == 'POST':
        email = request.POST.get('email')
        name = request.POST.get('name')
        roll = request.POST.get('roll')
        department = request.POST.get('department')
        session = request.POST.get('session')
        phone_number = request.POST.get('phone_number')
        address = request.POST.get('address')
        membership_number = request.POST.get('membership_number')
        user_type = request.POST.get('user_type')
        image = request.FILES.get('image')
        password = request.POST.get('password')

        # Check if the required fields are provided
        if email and user_type:
            user = User(
                email=email,
                name=name,
                roll=roll,
                department=department,
                session=session,
                phone_number=phone_number,
                address=address,
                membership_number=membership_number,
                user_type=user_type,
                image=image,
            )
            user.set_password(password)
            user.save()
            messages.success(request, 'User created successfully.')
            return redirect('login')  # Redirect to a success page or another URL
        else:
            messages.error(request, 'Please fill in all required fields.')

    return render(request, 'user/user_registration.html')

def update_user_status(request, user_id):
    
    if request.method == 'POST':
        
        user = get_object_or_404(User, id=user_id)
        # Update the is_active status
        user.is_active = request.POST.get('is_active') == 'on'
        user.save()
        # Redirect back to the user list or any other appropriate page
        return redirect('all_users') 

@login_required(login_url='login')
def update_user(request, user_id):
    # Get the user object by ID
    user = get_object_or_404(User, id=user_id)
    
    if request.method == 'POST':
        # Pass POST data and FILES to the form for validation
        form = UserForm1(request.POST, request.FILES, instance=user)
        
        if form.is_valid():
            form.save()  # Save the updated user object
            messages.success(request, 'User information updated successfully!')
            return redirect('profile_view')  # Redirect to a user list or another page
        else:
            messages.error(request, 'Please correct the errors below.')
    
    else:
        # If it's a GET request, populate the form with the existing user data
        form = UserForm1(instance=user)
    
    context = {
        'form': form,
        'user': user
    }
    return render(request, 'user/update_user.html', context)




@login_required(login_url='login')
def delete_user(request, user_id):
    
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        user.delete()
        return redirect('all_users')  # Redirect to 'all_users' after deletion
    return render(request, 'user/all_users.html')

templates/user/all_users.html
{% extends "base.html" %}

{% block content %}
<main>
<div style="padding: 0%;"> 
<div class="">
    <h1>Members</h1>
    <div style="margin-left: 1100px;">
        <a href="{% url 'create_user' %}" class="btn btn-primary" id="up"> Create New User</a>
    </div>
    <br>
    <form method="GET" action="">
        <div class="input-group mb-3">
            <input type="text" name="q" class="form-control" placeholder="Search users..." value="{{ search_query|default:'' }}">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>
    </form>
    <table id="customers" border="1"">
        <thead>
            <tr style="background-color: rgb(74, 200, 200); text-align: center;">
                <th>Image</th>
                <th>Name</th>
                <th>Email</th>
                <th>Roll</th>
                <th>Department</th>
                <th>Session</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Membership Number</th>
                <th>User Type</th>
                <th>Active</th>
                <th>Admin</th>
               
                
                <th colspan="4" id="mid">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr> 
                <td>
                {% if user.image %}
                    <img src="{{ user.image.url }}" alt="Profile Image" width="50" height="50">
                {% else %}
                    No Image
                {% endif %}
               </td>
               <td>{{ user.name }}</td>
               <td>{{ user.email }}</td>
                <td>{{ user.roll }}</td>
                <td>{{ user.department }}</td>
                <td>{{ user.session }}</td>
                <td>{{ user.phone_number }}</td>
                <td>{{ user.address }}</td>
                <td>{{ user.membership_number }}</td>
                <td>{{ user.get_user_type_display }}</td>
                {% comment %} <td>{{ user.is_active|yesno:"Yes,No" }}</td> {% endcomment %}
                <td>
                    <form method="POST" action="{% url 'update_user_status' user.id %}" style="display:inline;">
                        {% csrf_token %}
                        <input type="checkbox" name="is_active" {% if user.is_active %}checked{% endif %} onchange="this.form.submit();">
                    </form>
                </td>

                <td>{{ user.is_admin|yesno:"Yes,No" }}</td>
               
                <td>
                    <!-- Update URL with user.id -->
                    <a href="{% url 'update_user' user.id %}" class="btn btn-primary" id="up">Update</a>
                </td>
                <td>
                    <!-- Delete URL with user.id -->
                    <form method="post" action="{% url 'delete_user' user.id %}">
                        {% csrf_token %}
                        <button type="submit" class="box" >Delete</button>
                    </form>
                   
                </td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br><br>
    <!-- Link to the registration page -->
    
</div>
</div>   
</main>
{% endblock content %}

templates/user/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4>User Profile</h4>
                </div>
                <div class="card-body text-center">
               
                {% if user.image %}
                    <img src="{{ user.image.url }}" class="rounded-circle" width="150" alt="Profile Picture">
                {% else %}
                    <img src="/media/difult_img/মৌলভীবাজার-পলিটেকনিক-ইনস্টিটিউট.jpg" class="rounded-circle" width="150" alt="Default Profile Picture">
                {% endif %}
                                
                
                
                    <h5 class="mt-3">{{ user.name }}</h5>
                    <p class="text-muted">{{ user.email }}</p>
                </div>
            </div>
        </div> <br><br>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>Profile Details</h4>
                </div>
                <div class="card-body">
                    <p><strong>Full Name:</strong> {{ user.name }}</p>
                    <p><strong>Email:</strong> {{ user.email }}</p>
                    <p><strong>Phone Number:</strong> {{ user.phone_number }}</p>
                    <p><strong>Address:</strong> {{ user.address }}</p>
                    <p><strong>Department:</strong> {{ user.get_department_display }}</p>
                    <p><strong>Membership Number:</strong> {{ user.membership_number }}</p>
                </div>
                <a href="{% url 'update_user' user.id %}" class="btn btn-primary mt-3">Edit Profile</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/user/update_user.html
<!-- update_user.html -->
{% extends "base.html" %}
{% block content %}
<main>
    <div class="container-fluid px-4">
        <div class="card mb-4 mt-5">
            <div class="card-body">
                <h2 style="text-align: center;">Update User Information</h2>

                <form method="post" action="{% url 'update_user' user.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Render all fields with error handling -->
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-primary">Update User</button>
                    {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
                    <a href="{% url 'all_users' %}" class="btn btn-secondary mt-3">Cancel</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/user/user_registration.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="container-fluid px-4">
            <div class="card mb-4 mt-5">
                <div class="card-body">
                    <h2 style="text-align: center;">User Registration</h2>

                    <form method="post" action="{% url 'create_user' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group mt-3">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{ user.email|default_if_none:'' }}" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="roll">Roll</label>
                            <input type="number" class="form-control" id="roll" name="roll" value="{{ user.roll|default_if_none:'' }}" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="department">Department</label>
                            <select class="form-control" id="department" name="department" required>
                                <option value="CMT" {% if user.department == "CMT" %}selected{% endif %}>Computer Technology</option>
                                <option value="ENT" {% if user.department == "ENT" %}selected{% endif %}>Electronics Technology</option>
                                <option value="RAC" {% if user.department == "RAC" %}selected{% endif %}>Refrigeration and Air Conditioning Technology</option>
                                <option value="FD" {% if user.department == "FD" %}selected{% endif %}>Food Technology</option>
                            </select>
                        </div>
                        <div class="form-group mt-3">
                            <label for="session">Session</label>
                            <input type="text" class="form-control" id="session" name="session" value="{{ user.session|default_if_none:'' }}" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="phone_number">Phone Number</label>
                            <input type="text" class="form-control" id="phone_number" name="phone_number" value="{{ user.phone_number|default_if_none:'' }}" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="address">Address</label>
                            <textarea class="form-control" id="address" name="address" rows="3" required>{{ user.address|default_if_none:'' }}</textarea>
                        </div>
                        <div class="form-group mt-3">
                            <label for="user_type">User Type</label>
                            <select class="form-control" id="user_type" name="user_type" required>
                                <option value="MEM" {% if user.user_type == "MEM" %}selected{% endif %}>Member</option>
                                {% if user.user_type == 'LIB' or user.user_type == 'ADM' %}
                                <option value="LIB" {% if user.user_type == "LIB" %}selected{% endif %}>Librarian</option>
                                <option value="ADM" {% if user.user_type == "ADM" %}selected{% endif %}>Admin</option>
                                {% endif %}
                            </select>
                        </div>
                        <div class="form-group mt-3">
                            <label for="image">Profile Image</label><br>
                            <input type="file" class="form-control-file" id="image" name="image">
                            {% if user.image %}
                            <img src="{{ user.image.url }}" alt="Profile Image" width="100" height="100">
                            {% endif %}
                        </div>
                        <div class="mt-4 mb-0">
                            <button type="submit" class="btn btn-primary mt-3">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}